# Project information
site_name: "Interpretador: C++"
site_author: Grupo 7
site_description: >-
  Documentação do projeto de desenvolvimento de um Interpretador de C++ para Python, desenvolvido ao longo da disciplina de Compiladores 1 (2025/1) na Universidade de Brasília.

# Repository
repo_url: https://github.com/Maliz30/Interpretador_Cpp
repo_name: Interpretador_Cpp

# Configuration
docs_dir: docs
theme: 
  name: material
  language: pt-BR
  favicon: assets/logoBoa.png
  logo: assets/logoBoa.png
  icon: 
   repo: fontawesome/brands/github
  font: 
    text: Roboto
  features:
  - navigation.instant
  - navigation.section
  - navigation.path
  - navigation.top
  - navigation.tabs
  - navigation.tabs.sticky

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
      primary: deep purple
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro
        primary: deep purple
        accent: purple

extra_css: [stylesheets/extra.css]

# Page tree
nav: 
  - Início: 
    - Sobre: index.md
    - Como rodar: como-rodar.md
  - O Interpretador:
    - Como configurar o ambiente: interpretador/como-config.md
    - Subconjunto de C++ suportado: interpretador/subconjunto.md